version: "3"

services:
  mongo:
    image: mongo:4.4.13
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    env_file:
      - mongo.env
  telemetry:
    depends_on:
      - mongo
    build:
      context: .
    env_file:
      - telemetry.env
  broker:
    image: eclipse-mosquitto:1.6.9
    ports:
      - 1883:1883

volumes:
  mongo: